Repository iamrahulmahato/master-web-development, pull requests merged in 2024-10, with the labels that each got.

#47 tic tac toe tie popup added
  projects/Tic-tac-toe/app.js
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#46 Added Vocabulary Builder
  projects/Vocabulary Builder/Readme.md
  projects/Vocabulary Builder/addword.PNG
  projects/Vocabulary Builder/flashcard.PNG
  projects/Vocabulary Builder/index.html
  projects/Vocabulary Builder/quiz.PNG
  projects/Vocabulary Builder/script.js
  projects/Vocabulary Builder/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#75 Fixed issue #58 Adding Expense Tracker
  projects/Expense Tracker/index.html
  projects/Expense Tracker/script.js
  projects/Expense Tracker/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#74 Calculator Updated
  projects/Calculator/index.html
  projects/Calculator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#64 Enhanced Gradient Color Generator with Preview and Copy Functionality
  projects/GenerateGradientColor/gradient.css
  projects/GenerateGradientColor/gradient.js
  projects/GenerateGradientColor/index.html
  projects/GenerateGradientColor/script.js
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#76 added meme generator
  assets/image/images.png
  index.html
  projects/memeGen/index.html
  projects/memeGen/script.js
  projects/memeGen/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#91 Added "Number_guessing" feature
  index.html
  projects/Number guessing/index.html
  projects/Number guessing/script.js
  projects/Number guessing/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#95 input from keyboard
  projects/counter/index.html
  projects/counter/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#93 Sticky Notes Application
  projects/Sticky-Note/README.md
  projects/Sticky-Note/index.html
  projects/Sticky-Note/script.js
  projects/Sticky-Note/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#102 Word-Scramble
  projects/Word-Scrambble
  projects/word scramble/html.html
  projects/word scramble/script.js
  projects/word scramble/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#111 Typing speed test added
  projects/Typing Speed Test/app.js
  projects/Typing Speed Test/favicon.ico
  projects/Typing Speed Test/index.html
  projects/Typing Speed Test/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#109 Corrected Snake Game
  projects/Snake Game/README.md
  projects/Snake Game/index.html
  projects/Snake Game/script.js
  projects/Snake Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#133 Add Bubble Hit Game feature
  projects/Bubble Hit  Game/images/favicon.png
  projects/Bubble Hit  Game/index.html
  projects/Bubble Hit  Game/script.js
  projects/Bubble Hit  Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#100 Add 2048 Game
  App.js
  projects/2048/index.html
  projects/2048/script.js
  projects/2048/style.css
  public/styles.css
  routes/forum.js
  views/ask.ejs
  views/index.ejs
  views/layout.ejs
  views/question.ejs
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#124 Added Hexsweep Game
  projects/Hexsweep-Game/README.md
  projects/Hexsweep-Game/index.html
  projects/Hexsweep-Game/script.js
  projects/Hexsweep-Game/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#63 Memory Card Game
  projects/Memory Game/game.html
  projects/Memory Game/imgs/alien.png
  projects/Memory Game/imgs/amaze.png
  projects/Memory Game/imgs/amazed.png
  projects/Memory Game/imgs/angel.png
  projects/Memory Game/imgs/angry.png
  projects/Memory Game/imgs/angry2.png
  projects/Memory Game/imgs/attitude.png
  projects/Memory Game/imgs/shocked.png
  projects/Memory Game/index.html
  projects/Memory Game/script.js
  projects/Memory Game/style.css
  projects/Memory Game/win.html
  projects/memory-card-game-main
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#129 [FIX] Image link broken #114
  assets/image/numbers.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#92 Added 8_puzzle
  index.html
  projects/8_puzzle/Readme.md
  projects/8_puzzle/index.html
  projects/8_puzzle/script.js
  projects/8_puzzle/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#122 Added Wordle game
  index.html
  projects/Wordle Game/index.html
  projects/Wordle Game/script.js
  projects/Wordle Game/style.css
  projects/Wordle Game/wordle-logo.png
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#126 Weather section added
  css/style.css
  index.html
  js/app.js
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#158 Added bitcoin price detector
  projects/Bitcoin Detector/css/style.css
  projects/Bitcoin Detector/html/index.html
  projects/Bitcoin Detector/js/api.js
  projects/Bitcoin Detector/js/chart.js
  projects/Bitcoin Detector/js/dropdown.js
  projects/Bitcoin Detector/js/time.js
  projects/Bitcoin Detector/js/wallet.js
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#116 CHANGED THE LOOK OF THE WEBSITE ALSO ADDED A FEATURE OF ENTER KEY IS CHECK NOW. ISSUE #128
  projects/Number guessing/index.html
  projects/Number guessing/script.js
  projects/Number guessing/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#148 Adding Prisoner Dilemma game and Text Analyzer Tool
  projects/Prisoner Dilemma Game/Readme.md
  projects/Prisoner Dilemma Game/images/background_prisoners_dillema.jpeg
  projects/Prisoner Dilemma Game/images/prisoner1.jpg
  projects/Prisoner Dilemma Game/images/prisoner2.jpg
  projects/Prisoner Dilemma Game/index.html
  projects/Prisoner Dilemma Game/script.js
  projects/Prisoner Dilemma Game/style.css
  projects/Text-Analyzer/.gitignore
  projects/Text-Analyzer/README.md
  projects/Text-Analyzer/build/asset-manifest.json
  projects/Text-Analyzer/build/favicon.ico
  projects/Text-Analyzer/build/index.html
  projects/Text-Analyzer/build/manifest.json
  projects/Text-Analyzer/build/robots.txt
  projects/Text-Analyzer/build/static/css/main.63768210.css
  projects/Text-Analyzer/build/static/css/main.63768210.css.map
  projects/Text-Analyzer/build/static/js/453.56f46472.chunk.js
  projects/Text-Analyzer/build/static/js/453.56f46472.chunk.js.map
  projects/Text-Analyzer/build/static/js/main.6d40d0fd.js
  projects/Text-Analyzer/build/static/js/main.6d40d0fd.js.LICENSE.txt
  projects/Text-Analyzer/build/static/js/main.6d40d0fd.js.map
  projects/Text-Analyzer/package-lock.json
  projects/Text-Analyzer/package.json
  projects/Text-Analyzer/public/favicon.ico
  projects/Text-Analyzer/public/hii
  projects/Text-Analyzer/public/index.html
  projects/Text-Analyzer/public/manifest.json
  projects/Text-Analyzer/public/robots.txt
  projects/Text-Analyzer/src/App.css
  projects/Text-Analyzer/src/App.js
  projects/Text-Analyzer/src/App.test.js
  projects/Text-Analyzer/src/components/Aboutus.js
  projects/Text-Analyzer/src/components/Contact.js
  projects/Text-Analyzer/src/components/ContactForm.css
  projects/Text-Analyzer/src/components/Navbar.js
  projects/Text-Analyzer/src/components/Textform.js
  projects/Text-Analyzer/src/index.css
  projects/Text-Analyzer/src/index.js
  projects/Text-Analyzer/src/reportWebVitals.js
  projects/Text-Analyzer/src/setupTests.js
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#199 Added more information about the planets. #162
  projects/Plants/index.html
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#147 Added Custom password Length and copy button
  projects/Password Generator/index.html
  projects/Password Generator/script.js
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#163 Added Simon Game and Drum Kit
  assets/image/drum.png
  assets/image/simon_img.png
  index.html
  projects/Drum-kit/crash.mp3
  projects/Drum-kit/crash.png
  projects/Drum-kit/drum.css
  projects/Drum-kit/drum.js
  projects/Drum-kit/index.html
  projects/Drum-kit/kick-bass.mp3
  projects/Drum-kit/kick.png
  projects/Drum-kit/snare.mp3
  projects/Drum-kit/snare.png
  projects/Drum-kit/tom-1.mp3
  projects/Drum-kit/tom-2.mp3
  projects/Drum-kit/tom-3.mp3
  projects/Drum-kit/tom-4.mp3
  projects/Drum-kit/tom1.png
  projects/Drum-kit/tom2.png
  projects/Drum-kit/tom3.png
  projects/Drum-kit/tom4.png
  projects/Simon/blue.mp3
  projects/Simon/green.mp3
  projects/Simon/index.html
  projects/Simon/red.mp3
  projects/Simon/simon.css
  projects/Simon/simon.js
  projects/Simon/wrong.mp3
  projects/Simon/yellow.mp3
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#151 Added Live Clock and a Stop Watch in master-web=development
  assets/image/digital.png
  assets/image/stop.png
  index.html
  projects/Clock/index.html
  projects/Clock/script.js
  projects/Clock/style.css
  projects/Clock/v.png
  projects/Stop Watch/index.html
  projects/Stop Watch/rip.jpeg
  projects/Stop Watch/script.js
  projects/Stop Watch/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#185 Added a Hangman Game Project
  projects/Hangman/index.html
  projects/Hangman/script.js
  projects/Hangman/styles.css
Labels: question

#224 increase or decrease count when you long-press the + and - buttons
  projects/counter/index.html
Labels: question

#251 Dark Mode Card UI updated
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#261 [FIX] Counter icon animation added
  projects/counter/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#242 Added Connect4Dot Game file in the project folder
  assets/image/connect4-dot.png
  index.html
  projects/Connect4Dot/index.html
  projects/Connect4Dot/script.js
  projects/Connect4Dot/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#127 adding feature of bmi calculator#88
  index.html
  projects/bmi calculator/index.html
  projects/bmi calculator/javascript.js
  projects/bmi calculator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#268 Timer application feature - issue #154
  projects/timerapp/timer/index.html
  projects/timerapp/timer/script.js
  projects/timerapp/timer/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#295 Added Pizza Delight website with menu, cart, order, and reviews functionality
  projects/Online-Pizza-Shop/README.md
  projects/Online-Pizza-Shop/index.html
  projects/Online-Pizza-Shop/script.js
  projects/Online-Pizza-Shop/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#299 Improve Stopwatch UI with Modern Dark Theme and Interactive Buttons
  projects/Stop Watch/index.html
  projects/Stop Watch/script.js
  projects/Stop Watch/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#302 Sudoku Solver
  index.html
  projects/Sudoku Solver/image/1.png
  projects/Sudoku Solver/image/2.png
  projects/Sudoku Solver/image/pngegg.png
  projects/Sudoku Solver/index.html
  projects/Sudoku Solver/sudoku.js
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#292 add weather app
  assets/image/weather.jpg
  index.html
  projects/Weather App/app.js
  projects/Weather App/index.html
  projects/Weather App/styles.css
  projects/weather/images/clear.png
  projects/weather/images/clouds.png
  projects/weather/images/drizzle.png
  projects/weather/images/humidity.png
  projects/weather/images/mist.png
  projects/weather/images/rain.png
  projects/weather/images/search.png
  projects/weather/images/snow.png
  projects/weather/images/wind.png
  projects/weather/index.html
  projects/weather/script.js
  projects/weather/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#247 add github profile viewer
  assets/image/logo.png
  index.html
  projects/GenerateGradientColor/index.html
  projects/githubProfileViewer/index.html
  projects/githubProfileViewer/script.js
  projects/githubProfileViewer/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#272 Add drawing board project
  projects/Drawing-Board/index.html
  projects/Drawing-Board/script.js
  projects/Drawing-Board/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#277 add scroll to top button
  css/style.css
  index.html
  js/app.js
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#279 [FIX] Counting error fixed
  projects/counter/index.html
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#284 Photography_page Added
  projects/Photography_Page/index.html
  projects/Photography_Page/photo.jpg
  projects/Photography_Page/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#206 #145 updated counter application
  assets/image/counter.png
  index.html
  projects/counter/index.html
  projects/counter/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#244 Added code solution for addition of Pomodoro feature as stated in Issue #167
  projects/Todo List/index.html
  projects/Todo List/mixkit-software-interface-start-2574.wav
  projects/Todo List/script.js
  projects/Todo List/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#250 index.html
  projects/Plants/index.html
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#252 style.css
  projects/Plants/style.css
Labels: question

#269 added stick hero with canvas game
  assets/image/Stick-hero-with-canvas.png
  projects/Stick-Hero-With-Canvas/Readme.md
  projects/Stick-Hero-With-Canvas/index.html
  projects/Stick-Hero-With-Canvas/script.js
  projects/Stick-Hero-With-Canvas/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#296 [FIX] Wordle typo in landing page fixed
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#322 Created a Trivia game And designed the UI
  assets/image/TRIVIA.png
  index.html
  projects/TRIVIA/index.html
  projects/TRIVIA/script.js
  projects/TRIVIA/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#325 adding text to speech convertor and image generator feature #90
  index.html
  projects/Text to Speech/index.html
  projects/Text to Speech/script.js
  projects/Text to Speech/style.css
  projects/Text to Speech/txtsp.png
  projects/image Generator/index.html
  projects/image Generator/script.js
  projects/image Generator/search.png
  projects/image Generator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#360 Issue #233 - Typing Speed Test
  assets/image/Typing_test.jpg
  index.html
  projects/Typing Speed Test/index.html
  projects/Typing Test/Typing_test.jpg
  projects/Typing Test/index.html
  projects/Typing Test/script.js
  projects/Typing Test/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#361 Geography Quiz Game Feature Update
  assets/image/geography.png
  index.html
  projects/geography quiz/index.html
  projects/geography quiz/script.js
  projects/geography quiz/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#235 Sudoku webapplication
  assets/image/pastime.png
  index.html
  projects/sudoku/game.png
  projects/sudoku/index.html
  projects/sudoku/script.js
  projects/sudoku/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#412 Issue #410 resolved : Card changes
  css/style.css
  index.html
  projects/random user generator/index.css
  projects/random user generator/index.html
  projects/random user generator/index.js
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#304 Added Word counter app #Issue264
  assets/image/word-counter.png
  projects/Word-counter/index.html
  projects/Word-counter/script.js
  projects/Word-counter/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#317 enhanced ui for tic tac toe
  projects/Tic-tac-toe/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#367 Changed the UI of complete todo-app
  projects/Todo List/index.html
  projects/Todo List/pxfuel.jpg
  projects/Todo List/script.js
  projects/Todo List/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#373 Solved Issue #370 Generate Gradient not working
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#375 Puzzle game
  projects/puzzle-game/1.jpg
  projects/puzzle-game/10.jpg
  projects/puzzle-game/11.jpg
  projects/puzzle-game/12.jpg
  projects/puzzle-game/2.jpg
  projects/puzzle-game/3.jpg
  projects/puzzle-game/4.jpg
  projects/puzzle-game/5.jpg
  projects/puzzle-game/6.jpg
  projects/puzzle-game/7.jpg
  projects/puzzle-game/8.jpg
  projects/puzzle-game/9.jpg
  projects/puzzle-game/README.md
  projects/puzzle-game/index.html
  projects/puzzle-game/script.js
  projects/puzzle-game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2

#379 SUCCESSFULLY EHANCE THE USER INTERFACE OF THE PASSWORD GENERATOR APPL…
  assets/image/contact form image.svg
  assets/image/password generator main.svg
  community/frontend/contact.css
  community/frontend/contact.html
  community/frontend/contact.js
  community/frontend/style.css
  css/style.css
  index.html
  js/app.js
  projects/Password Generator/index.html
  projects/Password Generator/script.js
  projects/Password Generator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#382 Added game Among-Us
  projects/Among Us Game/assets/audio/Killing_Sound.mp3
  projects/Among Us Game/assets/audio/Sound.mp3
  projects/Among Us Game/assets/images/Amogus_Icon.png
  projects/Among Us Game/assets/images/Crewmate_killed.png
  projects/Among Us Game/assets/images/Crewmate_normal.png
  projects/Among Us Game/assets/images/Impostor_Killing.png
  projects/Among Us Game/assets/images/Impostor_normalWalk.png
  projects/Among Us Game/assets/images/Killing_Animation.png
  projects/Among Us Game/assets/images/Loading_Screen.jpg
  projects/Among Us Game/assets/images/The_Skeld_Cafeteria.png
  projects/Among Us Game/assets/images/kill_button.png
  projects/Among Us Game/index.html
  projects/Among Us Game/script.js
  projects/Among Us Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#395 Added Magic 8 ball
  index.html
  projects/Magic8Ball/index.html
  projects/Magic8Ball/magic8ball.png
  projects/Magic8Ball/script.js
  projects/Magic8Ball/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#396 Add contribute section
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#397 Improved the look of the BMI Calculator
  projects/bmi calculator/index.html
  projects/bmi calculator/javascript.js
  projects/bmi calculator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#401 added portfolio
  projects/codewithmeowmeowportfolio/images/1.jpg
  projects/codewithmeowmeowportfolio/images/2.jpg
  projects/codewithmeowmeowportfolio/images/3.jpg
  projects/codewithmeowmeowportfolio/images/4.jpg
  projects/codewithmeowmeowportfolio/images/cutout.jpg
  projects/codewithmeowmeowportfolio/images/impcutout.png
  projects/codewithmeowmeowportfolio/portfolio.css
  projects/codewithmeowmeowportfolio/portfolio.html
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#426 ADD CURRENCY CONVERTOR APP
  assets/image/currency.jpg
  index.html
  projects/Currency Convertor/R.jpg
  projects/Currency Convertor/index.html
  projects/Currency Convertor/script.js
  projects/Currency Convertor/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#434 Added Rock paper scissor
  assets/image/Rock-paper-scissor.png
  index.html
  projects/Rock Paper Scissors/Styles.css
  projects/Rock Paper Scissors/gameImages/paperComputer.png
  projects/Rock Paper Scissors/gameImages/paperPlayer.png
  projects/Rock Paper Scissors/gameImages/scissorsComputer.png
  projects/Rock Paper Scissors/gameImages/scissorsPlayer.png
  projects/Rock Paper Scissors/gameImages/stoneComputer.png
  projects/Rock Paper Scissors/gameImages/stonePlayer.png
  projects/Rock Paper Scissors/index.css
  projects/Rock Paper Scissors/index.html
  projects/Rock Paper Scissors/script.js
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#442 Add target blank , open the website in a new tab
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#466 Add doodle jump game
  assets/image/doodle.png
  index.html
  projects/Doodle Jump/doodlejump.css
  projects/Doodle Jump/doodlejump.js
  projects/Doodle Jump/doodlejumpbg.png
  projects/Doodle Jump/doodler-left.png
  projects/Doodle Jump/doodler-right.png
  projects/Doodle Jump/index.html
  projects/Doodle Jump/platform-broken.png
  projects/Doodle Jump/platform.png
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#470 added minecraft
  projects/minecraft/array.js
  projects/minecraft/assets/images/bgimg.jpg
  projects/minecraft/assets/images/blocks/Cursors/coal.cur
  projects/minecraft/assets/images/blocks/Cursors/diamond.cur
  projects/minecraft/assets/images/blocks/Cursors/grass.cur
  projects/minecraft/assets/images/blocks/Cursors/hatchet.cur
  projects/minecraft/assets/images/blocks/Cursors/leaves.cur
  projects/minecraft/assets/images/blocks/Cursors/pickaxe.cur
  projects/minecraft/assets/images/blocks/Cursors/ruby.cur
  projects/minecraft/assets/images/blocks/Cursors/shovel.cur
  projects/minecraft/assets/images/blocks/Cursors/stone.cur
  projects/minecraft/assets/images/blocks/Cursors/tree.cur
  projects/minecraft/assets/images/blocks/coal.png
  projects/minecraft/assets/images/blocks/diamond.png
  projects/minecraft/assets/images/blocks/grass.png
  projects/minecraft/assets/images/blocks/hatchet.png
  projects/minecraft/assets/images/blocks/leaves.png
  projects/minecraft/assets/images/blocks/pickaxe.png
  projects/minecraft/assets/images/blocks/ruby.png
  projects/minecraft/assets/images/blocks/shovel.png
  projects/minecraft/assets/images/blocks/stone.png
  projects/minecraft/assets/images/blocks/tree.png
  projects/minecraft/assets/images/chevleft.png
  projects/minecraft/assets/images/chevright.png
  projects/minecraft/assets/images/logo.png.png
  projects/minecraft/assets/sounds/boulders.mp3
  projects/minecraft/assets/sounds/minecraftclick.mp3
  projects/minecraft/assets/style/animations.css
  projects/minecraft/assets/style/game.css
  projects/minecraft/assets/style/reset.css
  projects/minecraft/assets/style/style.css
  projects/minecraft/game.html
  projects/minecraft/index.html
  projects/minecraft/modules/game.js
  projects/minecraft/modules/gridGenerator.js
  projects/minecraft/modules/index.js
  projects/minecraft/modules/tileGenerator.js
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#474 added CAR RACE GAME
  projects/CAR RACE/README.md
  projects/CAR RACE/images/1icon.png
  projects/CAR RACE/images/car04.png
  projects/CAR RACE/images/cloud.jpg
  projects/CAR RACE/images/finish.png
  projects/CAR RACE/images/hero.png
  projects/CAR RACE/images/icon.png
  projects/CAR RACE/images/tree.png
  projects/CAR RACE/index.html
  projects/CAR RACE/script.js
  projects/CAR RACE/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#480 Added Fruit Slicer game
  projects/Fruit Slicer/index.html
  projects/Fruit Slicer/script.js
  projects/Fruit Slicer/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#492 Updated the GitHub Profile Viewer
  projects/githubProfileViewer/index.html
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, nolevel

#493 Add password manager
  assets/image/Password-manager.png
  index.html
  projects/Password manager/R.jpg
  projects/Password manager/copy.svg
  projects/Password manager/esf.jpg
  projects/Password manager/index.html
  projects/Password manager/script.js
  projects/Password manager/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#497 Enhance Password Generator with Strength Meter and Improved UI
  projects/Password Generator/index.html
  projects/Password Generator/script.js
  projects/Password Generator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#472 Add among us game
  assets/image/amongus.png
  index.html
  projects/Among Us/audio/Killing_Sound.mp3
  projects/Among Us/audio/Sound.mp3
  projects/Among Us/images/Amogus_Icon.png
  projects/Among Us/images/Crewmate_killed.png
  projects/Among Us/images/Crewmate_normal.png
  projects/Among Us/images/Impostor_Killing.png
  projects/Among Us/images/Impostor_normalWalk.png
  projects/Among Us/images/Killing_Animation.png
  projects/Among Us/images/Loading_Screen.jpg
  projects/Among Us/images/The_Skeld_Cafeteria.png
  projects/Among Us/images/kill_button.png
  projects/Among Us/index.html
  projects/Among Us/script.js
  projects/Among Us/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#456 Add Slide Puzzle website
  assets/image/slide.png
  index.html
  projects/Slide Puzzle/1.jpg
  projects/Slide Puzzle/10.jpg
  projects/Slide Puzzle/2.jpg
  projects/Slide Puzzle/3.jpg
  projects/Slide Puzzle/4.jpg
  projects/Slide Puzzle/5.jpg
  projects/Slide Puzzle/6.jpg
  projects/Slide Puzzle/7.jpg
  projects/Slide Puzzle/8.jpg
  projects/Slide Puzzle/9.jpg
  projects/Slide Puzzle/index.html
  projects/Slide Puzzle/logo.png
  projects/Slide Puzzle/puzzle.css
  projects/Slide Puzzle/puzzle.js
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#438 Add Notes taking Website
  assets/image/Notes.webp
  index.html
  projects/Notes Taking Website/index.html
  projects/Notes Taking Website/js/App.js
  projects/Notes Taking Website/js/NoteApi.js
  projects/Notes Taking Website/js/NotesView.js
  projects/Notes Taking Website/js/main.js
  projects/Notes Taking Website/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#429 Favicon added
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, nolevel

#502 add email validator
  assets/image/email.png
  index.html
  projects/Email Validator/esf.jpg
  projects/Email Validator/img/email.svg
  projects/Email Validator/img/loading.svg
  projects/Email Validator/index.html
  projects/Email Validator/script.js
  projects/Email Validator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#506 Optimize Snake Game Performance
  projects/Snake Game/index.html
  projects/Snake Game/script.js
  projects/Snake Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#566 file is added
  projects/feedbck_form/pro.html
  projects/feedbck_form/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#513 Sucessfully added Tetris game #444
  assets/image/tetrsis.jpg
  index.html
  projects/Tetris_Game/index.html
  projects/Tetris_Game/script.js
  projects/Tetris_Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#523 added personal_finance_dashboard project issue no. 459
  projects/personal_finance_dashboard/index.html
  projects/personal_finance_dashboard/script.js
  projects/personal_finance_dashboard/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#545 Added the Connect4 game #482
  index.html
  projects/Connect4/Connectfour.png
  projects/Connect4/README.md
  projects/Connect4/connect4.css
  projects/Connect4/connect4.js
  projects/Connect4/index.html
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#553 Updated: "m" to "cm" in BMI Calculator
  projects/bmi calculator/index.html
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, nolevel

#554 Bug Fix in Ping Pong
  projects/Ping Pong Game/script.js
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, nolevel

#555 add maze game
  assets/image/maze.jpg
  index.html
  projects/Maze/bg.jpg
  projects/Maze/home.png
  projects/Maze/index.html
  projects/Maze/key.png
  projects/Maze/script.js
  projects/Maze/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#339 AddedPokedex
  assets/image/Pokedex.jpg
  index.html
  projects/Pokedex/index.html
  projects/Pokedex/script.js
  projects/Pokedex/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#398 Added hangman game
  index.html
  projects/Hangman Game/images/hangman image.jpg
  projects/Hangman Game/images/hangman-0.svg
  projects/Hangman Game/images/hangman-1.svg
  projects/Hangman Game/images/hangman-2.svg
  projects/Hangman Game/images/hangman-3.svg
  projects/Hangman Game/images/hangman-4.svg
  projects/Hangman Game/images/hangman-5.svg
  projects/Hangman Game/images/hangman-6.svg
  projects/Hangman Game/images/lost.gif
  projects/Hangman Game/images/victory.gif
  projects/Hangman Game/index.html
  projects/Hangman Game/scripts/script.js
  projects/Hangman Game/scripts/word-list.js
  projects/Hangman Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#415 Enhance Features in Tic Tac Toe
  index.html
  projects/Tic-tac-toe/app.js
  projects/Tic-tac-toe/index.html
  projects/Tic-tac-toe/style.css
  projects/Tic-tac-toe/win-sound1.wav
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#471 Add stick hero game
  assets/image/stick.png
  index.html
  projects/Stick Hero/index.html
  projects/Stick Hero/script.js
  projects/Stick Hero/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#527 Dad Jokes Generator Project Using Fetch API #489
  projects/Dad Jokes Generator/README.md
  projects/Dad Jokes Generator/index.html
  projects/Dad Jokes Generator/pngwing.com.png
  projects/Dad Jokes Generator/script.js
  projects/Dad Jokes Generator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#580 added loan calculator
  projects/loan_calculator/index.html
  projects/loan_calculator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#589 create virtual keyboard
  assets/image/vc.jpg
  index.html
  projects/Virtual Keyboard/bg.jpg
  projects/Virtual Keyboard/index.html
  projects/Virtual Keyboard/script.js
  projects/Virtual Keyboard/style.css
  projects/Virtual Keyboard/vc.jpg
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#565 Added Modern chair E-commerce project #318
  projects/Modern Chair E-commerce project/Modern chair site Overview
  projects/Modern Chair E-commerce project/chair1.png
  projects/Modern Chair E-commerce project/chair2.png
  projects/Modern Chair E-commerce project/chair3.png
  projects/Modern Chair E-commerce project/chair4.png
  projects/Modern Chair E-commerce project/chair5.png
  projects/Modern Chair E-commerce project/chair6.png
  projects/Modern Chair E-commerce project/color1.jpg
  projects/Modern Chair E-commerce project/color2.jpg
  projects/Modern Chair E-commerce project/color3.jpg
  projects/Modern Chair E-commerce project/color4.jpg
  projects/Modern Chair E-commerce project/color5.jpg
  projects/Modern Chair E-commerce project/color6.jpg
  projects/Modern Chair E-commerce project/favicon.ico
  projects/Modern Chair E-commerce project/index.html
  projects/Modern Chair E-commerce project/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#597 Add Minesweeper game to project list
  assets/image/minesweeper.jpeg
  index.html
  projects/minesweeper/index.html
  projects/minesweeper/script.js
  projects/minesweeper/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#598 Added Mini Social Network project
  projects/Mini-SocialMedia-Platform/README.md
  projects/Mini-SocialMedia-Platform/index.html
  projects/Mini-SocialMedia-Platform/script.js
  projects/Mini-SocialMedia-Platform/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#563 virtual Piano
  assets/image/piano.png
  index.html
  projects/Dsa_quiz_game/index.html
  projects/Dsa_quiz_game/script.js
  projects/Dsa_quiz_game/style.css
  projects/Typing Test/Typing_test.jpg
  projects/Typing Test/index.html
  projects/Typing Test/script.js
  projects/Typing Test/style.css
  projects/pionoGame/24-piano-keys/key01.mp3
  projects/pionoGame/24-piano-keys/key02.mp3
  projects/pionoGame/24-piano-keys/key03.mp3
  projects/pionoGame/24-piano-keys/key04.mp3
  projects/pionoGame/24-piano-keys/key05.mp3
  projects/pionoGame/24-piano-keys/key06.mp3
  projects/pionoGame/24-piano-keys/key07.mp3
  projects/pionoGame/24-piano-keys/key08.mp3
  projects/pionoGame/24-piano-keys/key09.mp3
  projects/pionoGame/24-piano-keys/key10.mp3
  projects/pionoGame/24-piano-keys/key11.mp3
  projects/pionoGame/24-piano-keys/key12.mp3
  projects/pionoGame/24-piano-keys/key13.mp3
  projects/pionoGame/24-piano-keys/key14.mp3
  projects/pionoGame/24-piano-keys/key15.mp3
  projects/pionoGame/24-piano-keys/key16.mp3
  projects/pionoGame/24-piano-keys/key17.mp3
  projects/pionoGame/24-piano-keys/key18.mp3
  projects/pionoGame/24-piano-keys/key19.mp3
  projects/pionoGame/24-piano-keys/key20.mp3
  projects/pionoGame/24-piano-keys/key21.mp3
  projects/pionoGame/24-piano-keys/key22.mp3
  projects/pionoGame/24-piano-keys/key23.mp3
  projects/pionoGame/24-piano-keys/key24.mp3
  projects/pionoGame/index.html
  projects/pionoGame/script.js
  projects/pionoGame/style.css
  projects/pionoGame/theme/music1.png
  projects/pionoGame/theme/music2.png
  projects/pionoGame/theme/music3.png
  projects/pionoGame/theme/music4.png
  projects/pionoGame/theme/music5.png
  projects/pionoGame/theme/music6.png
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#609 Fix: Add missing closing tag in Stick Hero card
  css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#400 Added whack a mole game #358
  assets/image/mole logo.png
  index.html
  projects/Whack a mole/index.html
  projects/Whack a mole/monty-mole.png
  projects/Whack a mole/pipe.png
  projects/Whack a mole/piranha-plant.png
  projects/Whack a mole/script.js
  projects/Whack a mole/soil.png
  projects/Whack a mole/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#676 Escape the Maze Game with Bot Solver (A* Algorithm)
  index.html
  projects/MazeGame/assests/logo.png
  projects/MazeGame/index.html
  projects/MazeGame/script.js
  projects/MazeGame/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#606 RecipeBook :Recipe Searching Section
  projects/RecipeBook Website/dish.png
  projects/RecipeBook Website/food.png
  projects/RecipeBook Website/index.html
  projects/RecipeBook Website/salad-png-42805.png
  projects/RecipeBook Website/script.js
  projects/RecipeBook Website/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#614 Update Ping Pong Game
  projects/Ping Pong Game/index.html
  projects/Ping Pong Game/script.js
  projects/Ping Pong Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#672 Added Sudoko Solver
  projects/Sudoko Solver/Readme.md
  projects/Sudoko Solver/index.html
  projects/Sudoko Solver/script.js
  projects/Sudoko Solver/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#650 Fix Bmi Calculator Website
  projects/bmi calculator/index.html
  projects/bmi calculator/javascript.js
  projects/bmi calculator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#608 added `PACKABUNCHAS` game
  projects/PACKABUNCHAS/README.md
  projects/PACKABUNCHAS/game.js
  projects/PACKABUNCHAS/index.html
  projects/PACKABUNCHAS/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#622 Fixed the issue #328: Added Image in Random User Generator
  projects/random user generator/index.css
  projects/random user generator/index.html
  projects/random user generator/index.js
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#626 added zero line game
  assets/image/zeroLine.png
  index.html
  projects/Zero Line Game/index.html
  projects/Zero Line Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#654 Add Building Blocks Game(3d Game)
  assets/image/buildingblock.png
  index.html
  projects/Building Block/index.html
  projects/Building Block/script.js
  projects/Building Block/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#670 Added WordSearch Game
  projects/WordSearch Game/index.html
  projects/WordSearch Game/script.js
  projects/WordSearch Game/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#688 A basic E-commerce fashion shop created using Html css
  projects/fashion shop/OIP.jpeg
  projects/fashion shop/app.jpg
  projects/fashion shop/b10.jpg
  projects/fashion shop/b17.jpg
  projects/fashion shop/b18.jpg
  projects/fashion shop/b2.jpg
  projects/fashion shop/b4.jpg
  projects/fashion shop/b7.jpg
  projects/fashion shop/f1.jpg
  projects/fashion shop/f1.png
  projects/fashion shop/f2.jpg
  projects/fashion shop/f2.png
  projects/fashion shop/f3.jpg
  projects/fashion shop/f3.png
  projects/fashion shop/f4.jpg
  projects/fashion shop/f4.png
  projects/fashion shop/f5.jpg
  projects/fashion shop/f5.png
  projects/fashion shop/f6.jpg
  projects/fashion shop/f6.png
  projects/fashion shop/f7.jpg
  projects/fashion shop/f8.jpg
  projects/fashion shop/hero.png
  projects/fashion shop/hero2.jpg
  projects/fashion shop/index.html
  projects/fashion shop/n1.jpg
  projects/fashion shop/n2.jpg
  projects/fashion shop/n3.jpg
  projects/fashion shop/n4.jpg
  projects/fashion shop/n5.jpg
  projects/fashion shop/n6.jpg
  projects/fashion shop/n7.jpg
  projects/fashion shop/n8.jpg
  projects/fashion shop/pay.png
  projects/fashion shop/play.jpg
  projects/fashion shop/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#556 Add a Candy Game
  assets/image/candy.png
  index.html
  projects/Candy Game/background.jpg
  projects/Candy Game/candy.css
  projects/Candy Game/candy.js
  projects/Candy Game/images/Blue-Striped-Horizontal.png
  projects/Candy Game/images/Blue-Striped-Vertical.png
  projects/Candy Game/images/Blue-Wrapped.png
  projects/Candy Game/images/Blue.png
  projects/Candy Game/images/Choco.png
  projects/Candy Game/images/Green-Striped-Horizontal.png
  projects/Candy Game/images/Green-Striped-Vertical.png
  projects/Candy Game/images/Green-Wrapped.png
  projects/Candy Game/images/Green.png
  projects/Candy Game/images/Orange-Striped-Horizontal.png
  projects/Candy Game/images/Orange-Striped-Vertical.png
  projects/Candy Game/images/Orange-Wrapped.png
  projects/Candy Game/images/Orange.png
  projects/Candy Game/images/Purple-Striped-Horizontal.png
  projects/Candy Game/images/Purple-Striped-Vertical.png
  projects/Candy Game/images/Purple-Wrapped.png
  projects/Candy Game/images/Purple.png
  projects/Candy Game/images/Red-Striped-Horizontal.png
  projects/Candy Game/images/Red-Striped-Vertical.png
  projects/Candy Game/images/Red-Wrapped.png
  projects/Candy Game/images/Red.png
  projects/Candy Game/images/Yellow-Striped-Horizontal.png
  projects/Candy Game/images/Yellow-Striped-Vertical.png
  projects/Candy Game/images/Yellow-Wrapped.png
  projects/Candy Game/images/Yellow.png
  projects/Candy Game/images/blank.png
  projects/Candy Game/index.html
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#638 Added Tempreature converter project : Issue no #584
  css/style.css
  projects/Temprature Converter/index.html
  projects/Temprature Converter/script.js
  projects/Temprature Converter/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#605 Added Gen AI Based Modern Quiz App
  projects/Gen-AI-Quiz-Application/components.json
  projects/Gen-AI-Quiz-Application/next-env.d.ts
  projects/Gen-AI-Quiz-Application/next.config.js
  projects/Gen-AI-Quiz-Application/package-lock.json
  projects/Gen-AI-Quiz-Application/package.json
  projects/Gen-AI-Quiz-Application/postcss.config.js
  projects/Gen-AI-Quiz-Application/public/logo.ico
  projects/Gen-AI-Quiz-Application/public/next.svg
  projects/Gen-AI-Quiz-Application/public/vercel.svg
  projects/Gen-AI-Quiz-Application/src/app/favicon.ico
  projects/Gen-AI-Quiz-Application/src/app/globals.css
  projects/Gen-AI-Quiz-Application/src/app/layout.tsx
  projects/Gen-AI-Quiz-Application/src/app/page.tsx
  projects/Gen-AI-Quiz-Application/src/categories.ts
  projects/Gen-AI-Quiz-Application/src/components/ui/button.tsx
  projects/Gen-AI-Quiz-Application/src/lib/ai.ts
  projects/Gen-AI-Quiz-Application/src/lib/common.ts
  projects/Gen-AI-Quiz-Application/src/lib/utils.ts
  projects/Gen-AI-Quiz-Application/tailwind.config.js
  projects/Gen-AI-Quiz-Application/tailwind.config.ts
  projects/Gen-AI-Quiz-Application/tsconfig.json
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#449 Created a virtual pet game
  assets/image/vp.jpg
  index.html
  projects/Virtual Pet Game/README.md
  projects/Virtual Pet Game/cat mouse.gif
  projects/Virtual Pet Game/dog.gif
  projects/Virtual Pet Game/index.html
  projects/Virtual Pet Game/script.js
  projects/Virtual Pet Game/style.css
  projects/Virtual Pet Game/turtle.gif
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#667 made the Chatbot
  assets/image/chat-7767693_1280.jpg
  index.html
  node_modules/.package-lock.json
  package-lock.json
  package.json
  projects/Chatbot/index.html
  projects/Chatbot/script.js
  projects/Chatbot/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#468 Add space invader
  assets/image/spaceinvade.png
  index.html
  projects/Space Invader/alien-cyan.png
  projects/Space Invader/alien-magenta.png
  projects/Space Invader/alien-yellow.png
  projects/Space Invader/alien.png
  projects/Space Invader/index.html
  projects/Space Invader/ship.png
  projects/Space Invader/space.css
  projects/Space Invader/space.js
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#512 added qr code generator :)
  assets/image/Mã_QR.png
  index.html
  projects/QR Generator/index.html
  projects/QR Generator/script.js
  projects/QR Generator/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#420 TrIbute Page
  projects/Tribute Page/Mah G.jpeg
  projects/Tribute Page/Tribute.html
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#694 #623 Space Collision Game Added
  index.html
  projects/Space Collision Game/img/bomb-icon-symbol-video-game.png
  projects/Space Collision Game/img/pixel-art-coin-money-icon-game.png
  projects/Space Collision Game/index.html
  projects/Space Collision Game/script.js
  projects/Space Collision Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#693 Added Computer Choice Feature
  projects/Rock Paper Scissors/Styles.css
  projects/Rock Paper Scissors/index.html
  projects/Rock Paper Scissors/script.js
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#652 Add Tilting Ball Game
  assets/image/tiltingmaze.png
  index.html
  projects/Tilting Maze Game/index.html
  projects/Tilting Maze Game/script.js
  projects/Tilting Maze Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#653 Add Train game
  assets/image/traintrack.png
  index.html
  projects/Train Track Game/1f441.svg
  projects/Train Track Game/1f4a5.svg
  projects/Train Track Game/1f4f7.svg
  projects/Train Track Game/1f682.svg
  projects/Train Track Game/1f9e8.svg
  projects/Train Track Game/fs.svg
  projects/Train Track Game/index.html
  projects/Train Track Game/script.js
  projects/Train Track Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#651 Add mario game
  assets/image/supermario.png
  index.html
  projects/Super Mario/css/reset.css
  projects/Super Mario/css/style.css
  projects/Super Mario/fonts/SuperMario256.ttf
  projects/Super Mario/images/back-btn.png
  projects/Super Mario/images/bg.png
  projects/Super Mario/images/bullet.png
  projects/Super Mario/images/clear-map-btn.png
  projects/Super Mario/images/coin.png
  projects/Super Mario/images/delete-all-btn.png
  projects/Super Mario/images/editor-btn.png
  projects/Super Mario/images/elements.png
  projects/Super Mario/images/enemies.png
  projects/Super Mario/images/flag-pole.png
  projects/Super Mario/images/flag.png
  projects/Super Mario/images/grid-large-btn.png
  projects/Super Mario/images/grid-medium-btn.png
  projects/Super Mario/images/grid-small-btn.png
  projects/Super Mario/images/grid.png
  projects/Super Mario/images/lvl-size.png
  projects/Super Mario/images/mario-head.png
  projects/Super Mario/images/mario-sprites.png
  projects/Super Mario/images/powerups.png
  projects/Super Mario/images/save-map-btn.png
  projects/Super Mario/images/saved-btn.png
  projects/Super Mario/images/slider-left.png
  projects/Super Mario/images/slider-right.png
  projects/Super Mario/images/start-btn.png
  projects/Super Mario/images/start-screen.png
  projects/Super Mario/index.html
  projects/Super Mario/js/GameUI.js
  projects/Super Mario/js/MarioMaker.js
  projects/Super Mario/js/Preloader.js
  projects/Super Mario/js/View.js
  projects/Super Mario/js/levelEditor/CreatedLevels.js
  projects/Super Mario/js/levelEditor/Editor.js
  projects/Super Mario/js/levelEditor/Storage.js
  projects/Super Mario/js/mainGame/Bullet.js
  projects/Super Mario/js/mainGame/Element.js
  projects/Super Mario/js/mainGame/Enemy.js
  projects/Super Mario/js/mainGame/GameSound.js
  projects/Super Mario/js/mainGame/Mario.js
  projects/Super Mario/js/mainGame/MarioGame.js
  projects/Super Mario/js/mainGame/PowerUp.js
  projects/Super Mario/js/mainGame/Score.js
  projects/Super Mario/sounds/bullet.wav
  projects/Super Mario/sounds/coin.wav
  projects/Super Mario/sounds/jump.wav
  projects/Super Mario/sounds/kill-enemy.wav
  projects/Super Mario/sounds/mario-die.wav
  projects/Super Mario/sounds/power-down.wav
  projects/Super Mario/sounds/power-up-appear.wav
  projects/Super Mario/sounds/power-up.wav
  projects/Super Mario/sounds/stage-clear.wav
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#404 Front-End Clone of Amazon Homepage
  assets/image/amazon_clone_card.jpeg
  index.html
  projects/clone_of_amazon/imgs/amazon_favicon.png
  projects/clone_of_amazon/imgs/amazon_logo.png
  projects/clone_of_amazon/imgs/box1_image.jpg
  projects/clone_of_amazon/imgs/box2_image.jpg
  projects/clone_of_amazon/imgs/box3_image.jpg
  projects/clone_of_amazon/imgs/box4_image.jpg
  projects/clone_of_amazon/imgs/box5_image.jpg
  projects/clone_of_amazon/imgs/box6_image.jpg
  projects/clone_of_amazon/imgs/box7_image.jpg
  projects/clone_of_amazon/imgs/box8_image.jpg
  projects/clone_of_amazon/imgs/hero_image.jpg
  projects/clone_of_amazon/index.html
  projects/clone_of_amazon/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#613 feat:Last War Game Added
  assets/image/Lastwar.png
  index.html
  projects/Last War Game/index.html
  projects/Last War Game/script.js
  projects/Last War Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#745 Add Color Guessing Game
  assets/image/colorguess.png
  index.html
  projects/Color Guessing Game/index.html
  projects/Color Guessing Game/script.js
  projects/Color Guessing Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#753 Add Alphabet Keyboard
  assets/image/alphabetkeyword.png
  index.html
  projects/Alphabet Keyboard/images/apple.png
  projects/Alphabet Keyboard/images/ball.png
  projects/Alphabet Keyboard/images/cat.png
  projects/Alphabet Keyboard/images/dog.png
  projects/Alphabet Keyboard/images/elephant.png
  projects/Alphabet Keyboard/images/fish.png
  projects/Alphabet Keyboard/images/fox.png
  projects/Alphabet Keyboard/images/grass.png
  projects/Alphabet Keyboard/images/hat.png
  projects/Alphabet Keyboard/images/insect.png
  projects/Alphabet Keyboard/images/jar.png
  projects/Alphabet Keyboard/images/kite.png
  projects/Alphabet Keyboard/images/lamp.png
  projects/Alphabet Keyboard/images/monkey.png
  projects/Alphabet Keyboard/images/nose.png
  projects/Alphabet Keyboard/images/ocean.png
  projects/Alphabet Keyboard/images/parrot.png
  projects/Alphabet Keyboard/images/queen.png
  projects/Alphabet Keyboard/images/rat.png
  projects/Alphabet Keyboard/images/sun.png
  projects/Alphabet Keyboard/images/tap.png
  projects/Alphabet Keyboard/images/umbrella.png
  projects/Alphabet Keyboard/images/violin.png
  projects/Alphabet Keyboard/images/water.png
  projects/Alphabet Keyboard/images/yellow.png
  projects/Alphabet Keyboard/images/zebra.png
  projects/Alphabet Keyboard/index.html
  projects/Alphabet Keyboard/index.js
  projects/Alphabet Keyboard/sounds/a.mp3
  projects/Alphabet Keyboard/sounds/b.mp3
  projects/Alphabet Keyboard/sounds/c.mp3
  projects/Alphabet Keyboard/sounds/d.mp3
  projects/Alphabet Keyboard/sounds/e.mp3
  projects/Alphabet Keyboard/sounds/f.mp3
  projects/Alphabet Keyboard/sounds/g.mp3
  projects/Alphabet Keyboard/sounds/h.mp3
  projects/Alphabet Keyboard/sounds/i.mp3
  projects/Alphabet Keyboard/sounds/j.mp3
  projects/Alphabet Keyboard/sounds/k.mp3
  projects/Alphabet Keyboard/sounds/l.mp3
  projects/Alphabet Keyboard/sounds/m.mp3
  projects/Alphabet Keyboard/sounds/n.mp3
  projects/Alphabet Keyboard/sounds/o.mp3
  projects/Alphabet Keyboard/sounds/p.mp3
  projects/Alphabet Keyboard/sounds/q.mp3
  projects/Alphabet Keyboard/sounds/r.mp3
  projects/Alphabet Keyboard/sounds/s.mp3
  projects/Alphabet Keyboard/sounds/t.mp3
  projects/Alphabet Keyboard/sounds/u.mp3
  projects/Alphabet Keyboard/sounds/v.mp3
  projects/Alphabet Keyboard/sounds/w.mp3
  projects/Alphabet Keyboard/sounds/x.mp3
  projects/Alphabet Keyboard/sounds/y.mp3
  projects/Alphabet Keyboard/sounds/z.mp3
  projects/Alphabet Keyboard/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#758 Added task search functionality
  projects/Todo List/index.html
  projects/Todo List/script.js
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#757 Add Magic Square
  assets/image/magicsquare.png
  index.html
  projects/Magic Square/index.html
  projects/Magic Square/script.js
  projects/Magic Square/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#760 Add LightHouse
  assets/image/lighthouse.png
  index.html
  projects/LightHouse/index.html
  projects/LightHouse/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#788 Added a simple temprature converter
  projects/temprature_converter/index.html
  projects/temprature_converter/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#697 #628 Added the Photo Gallery Project
  assets/image/Photo Gallery Image.png
  index.html
  projects/Photo Gallery/index.html
  projects/Photo Gallery/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#649 Add Lamb Lane game
  assets/image/lamblane.png
  index.html
  projects/Lamb Lane/index.html
  projects/Lamb Lane/script.js
  projects/Lamb Lane/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#727 Add Gorilla Game
  assets/image/gorillagame.png
  index.html
  projects/Gorilla Game/index.css
  projects/Gorilla Game/index.html
  projects/Gorilla Game/index.js
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#826 Made changes to photography project and password generator
  projects/Password Generator/bgblue.jpg
  projects/Password Generator/gradientblue.jpg
  projects/Password Generator/style.css
  projects/Photography_Page/baby_shoot.jpg
  projects/Photography_Page/cam.jpg
  projects/Photography_Page/camera.png
  projects/Photography_Page/dancer.jpg
  projects/Photography_Page/girly.jpg
  projects/Photography_Page/index.html
  projects/Photography_Page/lap.jpg
  projects/Photography_Page/man.png
  projects/Photography_Page/orng.jpg
  projects/Photography_Page/photo.jpg
  projects/Photography_Page/photography_img.jpg
  projects/Photography_Page/style.css
  projects/Photography_Page/sunset.jpeg
  projects/Photography_Page/wedding.jpeg
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#827 🔧 Feat: Add Auto comments action workflows
  .github/workflows/PR-merged.yml
  .github/workflows/PR-open.yml
  .github/workflows/issue-closed.yml
  .github/workflows/issue-open.yml
  node_modules/dotenv/CHANGELOG.md
  node_modules/dotenv/LICENSE
  node_modules/dotenv/README-es.md
  node_modules/dotenv/README.md
  node_modules/dotenv/config.d.ts
  node_modules/dotenv/config.js
  node_modules/dotenv/lib/cli-options.js
  node_modules/dotenv/lib/env-options.js
  node_modules/dotenv/lib/main.d.ts
  node_modules/dotenv/lib/main.js
  node_modules/dotenv/package.json
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#738 Add Christmas Bauble Game
  assets/image/christmasbauble.png
  index.html
  projects/Christmas Bauble/index.html
  projects/Christmas Bauble/script.js
  projects/Christmas Bauble/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#717 Add Air Ballon Game (Using canvas)
  assets/image/airballon.png
  index.html
  projects/Air Ballon Game/index.html
  projects/Air Ballon Game/script.js
  projects/Air Ballon Game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, nolevel

#668 integrate-bubble-game-to-website
  assets/image/bubbleposter.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#833 changed the weather app functionality
  projects/weather/index.html
  projects/weather/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level3, gssoc-ext

#715 functional and responsive To Do List App added : Issue no 585
  projects/L_To Do WebApp/To_Do_Background.jpg.png
  projects/L_To Do WebApp/index.html
  projects/L_To Do WebApp/script.js
  projects/L_To Do WebApp/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#821 box connet game #702
  assets/image/box connet game.png
  index.html
  projects/box connet game/box.css
  projects/box connet game/box.html
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#847 Added Text-to-Speech Reader Using Mozilla Voice API to address issue #505
  projects/mozilla-text-to-speech/.hintrc
  projects/mozilla-text-to-speech/README.md
  projects/mozilla-text-to-speech/img/angry.jpg
  projects/mozilla-text-to-speech/img/drink.jpg
  projects/mozilla-text-to-speech/img/food.jpg
  projects/mozilla-text-to-speech/img/grandma.jpg
  projects/mozilla-text-to-speech/img/happy.jpg
  projects/mozilla-text-to-speech/img/home.jpg
  projects/mozilla-text-to-speech/img/hurt.jpg
  projects/mozilla-text-to-speech/img/outside.jpg
  projects/mozilla-text-to-speech/img/sad.jpg
  projects/mozilla-text-to-speech/img/scared.jpg
  projects/mozilla-text-to-speech/img/school.jpg
  projects/mozilla-text-to-speech/img/speech-to-text.png
  projects/mozilla-text-to-speech/img/tired.jpg
  projects/mozilla-text-to-speech/index.html
  projects/mozilla-text-to-speech/script.js
  projects/mozilla-text-to-speech/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#751 Add Url Shortner
  assets/image/url.png
  index.html
  projects/url shortener/bg.jpg
  projects/url shortener/index.html
  projects/url shortener/script.js
  projects/url shortener/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#761 Fixed issue #330: Wrong Redirection in Home Page for Number Guessing game
  community/frontend/index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext

#739 #604 Added Virtual Zen Garden Game
  projects/Virtual Zen Garden/images/plant1.png
  projects/Virtual Zen Garden/images/plant2.jpg
  projects/Virtual Zen Garden/images/plant3.jpg
  projects/Virtual Zen Garden/images/rock1.png
  projects/Virtual Zen Garden/images/rock2.png
  projects/Virtual Zen Garden/images/rock3.png
  projects/Virtual Zen Garden/index.html
  projects/Virtual Zen Garden/script.js
  projects/Virtual Zen Garden/style.css
Labels: hacktoberfest, hacktoberfest-accepted, level2, gssoc-ext

#898 Added code editor
  projects/Code Compiler/README.md
  projects/Code Compiler/background.js
  projects/Code Compiler/manifest.json
  projects/Code Compiler/popup.html
  projects/Code Compiler/popup.js
  projects/Code Compiler/server.js
Labels: hacktoberfest, hacktoberfest-accepted, level1, gssoc-ext
